import logging
import os
import re
from datetime import datetime, timezone
import resend
from flask import Blueprint, jsonify, request

logger = logging.getLogger("soc.email_report")
bp = Blueprint("email_report", __name__)

def is_valid_email(email: str) -> bool:
    pattern = r"^[^\s@]+@[^\s@]+\.[^\s@]+$"
    return re.match(pattern, email) is not None

def get_color_for_threat(level: str) -> str:
    if level == "HIGH": return "#ef4444"
    if level == "MEDIUM": return "#f59e0b"
    return "#22c55e"

@bp.route("/send-report-email", methods=["POST"])
def send_report_email():
    try:
        data = request.get_json()
        if not data:
            return jsonify({"success": False, "error": "Invalid JSON payload"}), 400
            
        recipient = data.get("email", "").strip()
        report_text = data.get("report", "")
        threat_level = data.get("threat_level", "LOW").upper()

        if not is_valid_email(recipient):
            return jsonify({"success": False, "error": "Invalid email format"}), 400
            
        if not report_text:
            return jsonify({"success": False, "error": "Report text cannot be empty"}), 400

        resend_key = os.environ.get("RESEND_API_KEY")
        if not resend_key:
            return jsonify({"success": False, "error": "RESEND_API_KEY not configured"}), 500

        resend.api_key = resend_key

        color = get_color_for_threat(threat_level)
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        report_html = report_text.replace('\n', '<br>')

        html_body = f"""
        <html>
        <body style="background-color: #0a0a0a; color: #e5e7eb; font-family: monospace; padding: 20px;">
            <div style="border: 1px solid {color}; padding: 20px; border-radius: 8px; max-width: 800px; margin: 0 auto; background-color: #111;">
                <h2 style="color: {color}; margin-top: 0; display: flex; align-items: center; border-bottom: 1px solid #333; padding-bottom: 10px;">
                    <span style="margin-right: 10px;">🚨</span> THREAT LEVEL: {threat_level}
                </h2>
                <div style="color: #9ca3af; margin-bottom: 20px; font-size: 12px;">
                    🕐 GENERATED AT: {timestamp} (Server Time)
                </div>
                <div style="background-color: #000; padding: 15px; border-radius: 4px; border: 1px solid #333; line-height: 1.6;">
                    {report_html}
                </div>
                <div style="margin-top: 20px; color: #6b7280; font-size: 12px; text-align: center; border-top: 1px solid #333; padding-top: 10px;">
                    🤖 Generated by AI Threat Detection SOC Dashboard
                </div>
            </div>
        </body>
        </html>
        """

        params = {
            "from": "SOC Dashboard <onboarding@resend.dev>",
            "to": [recipient],
            "subject": f"🚨 SOC Incident Report - {threat_level} Threat Detected",
            "html": html_body,
        }

        r = resend.Emails.send(params)
        
        return jsonify({"success": True, "message": f"Report sent to {recipient}"})

    except Exception as e:
        logger.error(f"Error sending email via Resend: {str(e)}")
        return jsonify({"success": False, "error": str(e)}), 500
